### ISSUE TITLE
access to Frink machine, install julia there locally, run you scripts on the server to test that evething works

### ISSUE THREAD

**Issue by alexanderpanchenko** [suhasbhairav/JuliaMachineLearning#1]

**Comment by suhasbhairav** [comment]
Julia has been installed from source and is working fine on the server.
AdaGram cannot be installed because it requires clang to be built. I do not have permissions to install clang.
5 GB Wacky corpus has been downloaded on the server. The file has been tokenized and the dictionary file has been generated. But the model cannot be trained unless AdaGram is installed.

**Comment by alexanderpanchenko** [comment]
please write to Eugen Ruppert (check LT home page lt.informatik.tu-darmstadt.de) and ask to install Clang. Please tell that I asked to do so and you need to have this package to accomplish your assignment.

**Comment by suhasbhairav** [comment]
I figured out a way to build using gcc by removing clang out of the build code. The model is currently being trained on the server. (Also, sent a mail to Mr. Eugen Ruppert that clang installation is no longer required.)

**Comment by alexanderpanchenko** [comment]
great. please create a short instuction here on how to install julia and adagram on the server (step by step).

**Comment by suhasbhairav** [comment]
The file containing the steps for Julia and AdaGram installation on the frink server has been uploaded. (Julia_and_AdaGram_Installation.txt)

**Comment by alexanderpanchenko** [comment]
please just copy contents of this file here

**Comment by alexanderpanchenko** [comment]
OK. Thank you
